### ISSUE TITLE
Feature Request: Add `exportparts` to the poster `<img>` element so we can style it

### ISSUE THREAD

**Issue by NashJames** [muxinc/elements#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Description

This exists for the `<video>` element so I'm not certain why there isn't another one for the `<img>` element. I've spent nearly a day trying to add a border-radius to both elements but the docs don't cover some of these examples and were slightly misleading. The description seemed to imply that you could build something like the below example, in order to style a child element:

```css
  mux-player::part(poster-layer img) {
    border-radius: 1.5rem;
  }
```

I'm testing this out in work to see if we'd like to use purchase your video service so I'd appreciate a quick release with this if possible (I have some design guidelines I need to meet to demo). I noticed https://github.com/muxinc/elements/pull/384 which might be of some help.

Might also be worth an update to the docs to include an example such as mine for future reference.

### Expected Behavior

This or similar should work:
```css
  mux-player::part(video),
  mux-player::part(image) {
    border-radius: 1.5rem;
  }
```
